apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod

resources:
  - ../base

images:
  - name: DOCKERHUB_USERNAME/simple-nginx-app
    newName: DOCKERHUB_USERNAME/simple-nginx-app
    newTag: prod

replicas:
  - name: simple-nginx-app
    count: 2
